services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - INTRASTEK_DATABASE_URL=mysql://root:root@localhost:3306/intrastek-db

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - API_PORT=8000

  db:
    image: mysql:9.0
    command: --lower_case_table_names=1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=intrastek-db
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prisma
    ports:
      - '3306:3306'
